# Generated by Django 6.0.6 on 2026-07-08 03:32

from django.db import migrations, models
from django.db.models import F


def rename_and_migrate(apps, schema_editor):
    Hostel = apps.get_model('hostel_app', 'Hostel')
    Room = apps.get_model('hostel_app', 'Room')
    StudentProfile = apps.get_model('hostel_app', 'StudentProfile')

    Hostel.objects.filter(name='Emerald Hall').update(name='Men Accommodation', gender_type='MALE')
    Hostel.objects.filter(name='Burgundy Tower').update(name='Ladies Accommodation', gender_type='FEMALE')

    try:
        cream_oasis = Hostel.objects.get(name='Cream Oasis')
    except Hostel.DoesNotExist:
        return

    target_hostels = {
        'MALE': Hostel.objects.filter(name='Men Accommodation').first(),
        'FEMALE': Hostel.objects.filter(name='Ladies Accommodation').first(),
    }

    for profile in StudentProfile.objects.filter(room__hostel=cream_oasis):
        target_hostel = target_hostels.get(profile.gender.upper())
        if not target_hostel:
            continue

        room = Room.objects.filter(hostel=target_hostel, occupancy__lt=F('capacity')).order_by('id').first()
        profile.room = room
        profile.is_allocated = bool(room)
        profile.save(update_fields=['room', 'is_allocated'])

    cream_oasis.delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_and_migrate, reverse_code=reverse_func),
    ]
